site_name: A Smarter Way to Learn JavaScript
theme:
  name: windmill

# Configuration for GitHub Pages deployment
# repo_url: https://github.com/sheikh-mohammad/a-smarter-way-to-learn-javascript-book
# repo_name: a-smarter-way-to-learn-javascript-book
# edit_uri: edit/main/docs/

# # Page tree structure
nav:
  - Home: index.md
  - How to Use This Book: book_usage.md
  - Alerts: chapter_01_alerts.md
  - Variables for Strings: chapter_02_variables_for_strings.md
  - Variables for Numbers: chapter_03_variables_for_numbers.md
  - Variables Names Legal and Illegal: chapter_04_variable_names_legal_and_illegal.md
  - Math Expressions - Fimiliar Operators: chapter_05_math_expressions_familiar_operators.md
  - Math Expressions - Unfimiliar Operators: chapter_06_math_expressions_unfamiliar_operators.md

# Extra configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sheikh-mohammad/a-smarter-way-to-learn-javascript-book
