[project]
name = "a-smarter-way-to-learn-javascript-book"
version = "1.11.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-windmill>=1.0.5",
]
