name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main # or master, depending on your default branch
    # Optionally, specify paths to only run when documentation changes
    paths:
      - "docs/**"
    #   - 'mkdocs.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write # Required for the actions/deploy-pages action
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install mkdocs mkdocs-windmill # Install MkDocs and optional themes/plugins
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force --verbose
